'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
0


import { CacheProvider } from "@chakra-ui/next-js";
// import { ChakraProvider,  } from "@chakra-ui/react";

import { ChakraProvider, ColorModeScript } from '@chakra-ui/react'
import {
  extendTheme,
  withDefaultColorScheme,
  theme as baseTheme,
} from '@chakra-ui/react'

const TEXT_COLOR = '#4A4A4A'
const BORDER = '#B3B3B3'
const BUTTON_COLOR = '#FFDD00'

const customTheme = extendTheme(
  {
    styles: {
      global: {
        // styles for the `body`
        body: {
          // bg: 'gray.400',
          // color: 'white',
        },
        button: {
          color: BUTTON_COLOR,
        },
      },
    },
    fonts: {
      body: "system-ui, sans-serif",
      heading: "system-ui, sans-serif",
      mono: "Menlo, monospace",
    },
    colors: {
      brand: {
        100: '#FFED7A',
        200: '#FFEA65',
        300: '#FFE751',
        400: '#FFE53D',
        500: '#FFDD00',
        600: '#DABD00',
        700: '#B69D00',
        800: '#917E00',
        900: '#6D5E00',
      },
    },
    components: {
      Button: {
        baseStyle: {
          color: BUTTON_COLOR,
          fontWeight: 'semibold', // Normally, it is "semibold"
        },
        variants: {
          outline: {
            borderColor: BORDER,
            color: TEXT_COLOR
          },
          solid: {
            bg: 'brand.500',
            color: TEXT_COLOR
          },
          ghost: {
            color: TEXT_COLOR
          }
        },
      },
    },
  },
  withDefaultColorScheme({ colorScheme: 'brand' }),
)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ColorModeScript initialColorMode="dark" />
        <ChakraProvider 
          theme={customTheme}>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
